---
- name: Primer playbook
  hosts: webserver01
  remote_user: aminaya
  become: True
  tasks:
    - name: Copias /etc/hosts
      copy: src=/etc/hosts dest=/home/aminaya
      
- name: Segundo playbook
  hosts: webserver02
  remote_user: aminaya
  become: True
  tasks:
    - name: Copias /etc/hosts
      copy: src=/etc/hosts dest=/home/aminaya