- name: playbook para la clase de register
  hosts: localhost
  tasks:
    - name: Ejecutar comando uptime
      command: uptime
      register: salida_uptime
    - name: Visualiar variable
      debug: var=salida_uptime
