- name: playbook para la clase de register
  hosts: localhost
  tasks:
    - name: Ejecutar comando uptime
      command: cat /etc/hosts
      register: salida
    - name: Visualiar variable
#      debug: var=salida_uptime
      debug: var=salida.stdout_lines
