- name: Trabajar con modulo utiles
  hosts: localhost
  become: True
  tasks:

    - script: scripts/uptime.sh
    - shell: uptime >> uptime.log
      args:
        chdir: /tmp
    # - name: install pexpec
    #   yum: name=pexpect state=latest
    # - command: uname -a removes=/tmp/noejecutar
    # - expect:
    #     command: passwd aminaya
    #     responses:
    #       (?i)password: "acmc0885"
