- name: Trabajar con modulo utiles 03
  hosts: localhost
  vars:
    - numero: 10
  tasks:
    - debug: msg="Hostname {{ ansible_hostname }} FQDN {{ ansible_fqdn }}"
    - command: uptime
      register: salida
    - debug: var=salida
    - fail: msg="Numero no es 10"
      when: numero != 10

    - pause: prompt="Pausa ordenada del proceso" seconds=5
    - assert:
         msg: "Numero tiene que estar entre 0 y 100"
         that:
           - numero <= 100
           - numero > 0
