- name: example files module and openssl
  hosts: webserver02
  become: True
  tasks:
    - name: creating file with specific contend
      copy: content="this is a example v2" dest="/tmp/prueba" backup=yes
    - name: capture the content in a variable
      command: "ls -lthr /tmp/"
      register: output
    - name: visualize the content creating before
      debug: var=output
