- name: example files module and openssl
  hosts: webserver02
  become: True
  tasks:
    - name: creating file with specific contend
      copy: content="this is a example v2" dest="/tmp/prueba" backup=yes
    - name: file properties
      file: path="/tmp/prueba" backup=yes mode="777" owner="aminaya" group="aminaya"
    - name: delete file prueba
      file: path="/tmp/prueba" state=absent backup=yes
    - name: using stat module
      stat: path="/etc/services"
      register: output
    - name: visualize the content creating before
      debug: var=output
    - name: verify directory exists
      file:
        path: "/var/log/journal"
        state: directory
        owner: root
        group: systemd-journal
        mode: 2755
      notify: reiniciar_journald
  handlers:
    - name: reiniciar_journald
      service: name=systemd-journald state=restarted
