- name: Trabajar con modulo packing 2
  hosts: webserver02
  become: True
  tasks:

    - name: Actualizar lista de paquetes
      apt: update_cache=yes
    - name: Actualizar paquetes
      apt: upgrade=dist
    - name: Instalar nginx
      apt: name=nginx state=latest
    - name: agregamos clave apt
      apt_key:
        url: "https://ftp-master.debian.org/keys/archive-key-6.0.asc"
        state: present 
