- name: Trabajar con modulo set fact
  hosts: webserver02
  become: true
  tasks:
    - name: Esperamos hasta que el fichero exista
      wait_for: path=/tmp/exista delay=2
    - name: Esperamos hasta que el fichero no exista
      wait_for: path=/tmp/exista state=absent
